version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_auth
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: product_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_auth
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver_auth
    restart: unless-stopped
    ports:
      - "8843:8843"
    environment:
      CB_SECURITY_ALLOW_ANONYMOUS: "true"
    depends_on:
      - mysql

volumes:
  mysql_data:
